#!/bin/sh

wget -c https://archive.org/download/derbycon4/Closing-Ceremony.mp4
wget -c https://archive.org/download/derbycon4/Hacking-The-Media-For-Fame-And-Profit-Jenn-Ellis-Steven-Regan.mp4
wget -c https://archive.org/download/derbycon4/Parenteing-In-Infosec-Rafal-Los.mp4
wget -c https://archive.org/download/derbycon4/Red-Teaming-Back-and-Forth-5ever-Fuzzynop.mp4
wget -c https://archive.org/download/derbycon4/So-You-Want-To-Murder-a-Software-Patent-Jason-Scott.mp4
wget -c https://archive.org/download/derbycon4/Soft-Skills-for-a-Technical-World-Justin-Herman.mp4
wget -c https://archive.org/download/derbycon4/The-Achilles-Heel-Of-The-Banking-System.mp4
wget -c https://archive.org/download/derbycon4/no-audio-t418-A-Bug-or-Malware-Catastrophic-consequences-either-way-Benjamin-Holland-and-Suresh-Kothari.mp4
wget -c https://archive.org/download/derbycon4/t100-Welcome-to-the-Family-Intro.mp4
wget -c https://archive.org/download/derbycon4/t101-Hackers-saving-the-world-from-the-zombie-apocalypse-Johnny-Long.mp4
wget -c https://archive.org/download/derbycon4/t102-How-to-Give-the-Best-Pen-Test-of-Your-Life-Ed-Skoudis.mp4
wget -c https://archive.org/download/derbycon4/t103-Adaptive-Pentesting-Part-Two-Keynote-Kevin-Mitnick-and-Dave-Kennedy.mp4
wget -c https://archive.org/download/derbycon4/t104-If-it-fits-it-sniffs-Adventures-in-WarShipping-Larry-Pesce.mp4
wget -c https://archive.org/download/derbycon4/t105-Abusing-Active-Directory-in-Post-Exploitation-Carlos-Perez.mp4
wget -c https://archive.org/download/derbycon4/t106-Quantifying-the-Adversary-Introducing-GuerillaSearch-and-GuerillaPivot-Dave-Marcus.mp4
wget -c https://archive.org/download/derbycon4/t107-A-Year-in-the-Backdoor-Factory-Joshua-Pitts.mp4
wget -c https://archive.org/download/derbycon4/t108-Ball-and-Chain-A-New-Paradigm-in-Stored-Password-Security-Benjamin-Donnelly-and-Tim-Tomes.mp4
wget -c https://archive.org/download/derbycon4/t109-Et-tu-Kerberos-Christopher-Campbell.mp4
wget -c https://archive.org/download/derbycon4/t110-Advanced-Red-Teaming-All-Your-Badges-Are-Belong-To-Us-Eric-Smith.mp4
wget -c https://archive.org/download/derbycon4/t111-Bypassing-Internet-Explorers-XSS-Filter-Carlos-Munoz.mp4
wget -c https://archive.org/download/derbycon4/t112-Interceptor-A-PowerShell-SSL-MITM-Script-Casey-Smith.mp4
wget -c https://archive.org/download/derbycon4/t113-More-New-Shiny-in-the-Metasploit-Framework-Egypt.mp4
wget -c https://archive.org/download/derbycon4/t115-The-Human-Buffer-Overflow-aka-Amygdala-Hijacking-Christopher-Hadnagy.mp4
wget -c https://archive.org/download/derbycon4/t116-Shellcode-Time-Come-on-Grab-Your-Friends-Wartortell.mp4
wget -c https://archive.org/download/derbycon4/t117-The-Internet-Of-Insecure-Things-10-Most-Wanted-List-Paul-Asadoorian.mp4
wget -c https://archive.org/download/derbycon4/t118-DDoS-Botnet-1000-Knives-and-a-Scalpel-Josh-Abraham.mp4
wget -c https://archive.org/download/derbycon4/t119-wifu2-Cameron-Maerz.mp4
wget -c https://archive.org/download/derbycon4/t120-Attacking-Microsoft-Kerberos-Kicking-the-Guard-Dog-of-Hades-Tim-Medin.mp4
wget -c https://archive.org/download/derbycon4/t121-Introducing-Network-Scout-Defending-The-Soft-Center-of-Your-Network-Bill-oncee-Gardner-Aaedan-SomerVille-Shawn-Jordan.mp4
wget -c https://archive.org/download/derbycon4/t122-Getting-Windows-to-Play-with-Itself-A-Pen-Testers-Guide-to-Windows-API-Abuse-Brady-Bloxham.mp4
wget -c https://archive.org/download/derbycon4/t124-Protocol-Me-Maybe-How-to-Date-SCADA-Stephen-Hilt.mp4
wget -c https://archive.org/download/derbycon4/t125-Attacks-and-Countermeasures-Advanced-Network-Traffic-Manipulation-Matt-Kelly-and-Ryan-Reynolds.mp4
wget -c https://archive.org/download/derbycon4/t126-What-to-expect-when-youre-expectinga-pentest-Martin-Bos-and-Eric-Milam.mp4
wget -c https://archive.org/download/derbycon4/t200-Threat-Modeling-for-Realz-Bruce-Potter.mp4
wget -c https://archive.org/download/derbycon4/t201-A-Guided-Tour-of-the-Internet-Ghetto-Introduction-to-Tor-Hidden-Services-Brent-Huston.mp4
wget -c https://archive.org/download/derbycon4/t203-How-not-to-suck-at-pen-testing-John-Strand.mp4
wget -c https://archive.org/download/derbycon4/t204-Mainframes-Mopeds-and-Mischief-A-PenTesters-Year-in-Review-Tyler-Wrightson.mp4
wget -c https://archive.org/download/derbycon4/t205-The-Multibillion-Dollar-Industry-Thats-Ignored-Jason-Montgomery-and-Ryan-Sevey.mp4
wget -c https://archive.org/download/derbycon4/t206-Code-Insecurity-or-Code-in-Security-Mano-dash4rk-Paul.mp4
wget -c https://archive.org/download/derbycon4/t207-C3CM-Defeating-the-Command-Control-and-Communications-of-Digital-Assailants-Russ-McRee.mp4
wget -c https://archive.org/download/derbycon4/t208-Attack-Paths-Breaking-Into-Infosec-From-IT-Or-Other-Totally-Different-Fields-Eve-Adams-and-Johnny-Xmas.mp4
wget -c https://archive.org/download/derbycon4/t209-How-to-Secure-and-Sys-Admin-Windows-like-a-Boss-Jim-Kennedy.mp4
wget -c https://archive.org/download/derbycon4/t210-Red-white-and-blue-Making-sense-of-Red-Teaming-for-good-Ian-Amit.mp4
wget -c https://archive.org/download/derbycon4/t211-Around-the-world-in-80-Cons-Jayson-E-Street.mp4
wget -c https://archive.org/download/derbycon4/t212-Mirage-Next-Gen-Honeyports-Adam-Crompton-and-Mick-Douglas.mp4
wget -c https://archive.org/download/derbycon4/t214-Active-Directory-Real-Defense-for-Domain-Admins-Jason-Lang.mp4
wget -c https://archive.org/download/derbycon4/t215-The-Wireless-World-of-the-Internet-of-Things-JP-Dunning-ronin.mp4
wget -c https://archive.org/download/derbycon4/t216-Open-Source-Threat-Intelligence-Developing-a-Threat-intelligence-program-using-open-source-tools-and-public-sources-Edward-McCabe.mp4
wget -c https://archive.org/download/derbycon4/t218-Hacking-Mainframes-Vulnerabilities-in-applications-exposed-over-TN3270-Dominic-White.mp4
wget -c https://archive.org/download/derbycon4/t219-Single-Chip-Microcontrollers-Beyond-Arduino-Tharon-Hall.mp4
wget -c https://archive.org/download/derbycon4/t220-Building-Better-Botnets-with-IPv6-Code2.mp4
wget -c https://archive.org/download/derbycon4/t221-Bad-Advice-Unintended-Consequences-and-Broken-Paradigms-Think-Act-Different-Steve-Werby.mp4
wget -c https://archive.org/download/derbycon4/t222-Simple-Network-Management-Pwnd-Deral-Heiland-and-Matthew-Kienow.mp4
wget -c https://archive.org/download/derbycon4/t300-Patching-the-Human-Vulns-Leonard-Isham.mp4
wget -c https://archive.org/download/derbycon4/t301-Burp-For-All-Languages-Tom-Steele.mp4
wget -c https://archive.org/download/derbycon4/t302-Passing-the-Torch-Old-School-Red-Teaming-New-School-Tactics-David-McGuire-and-Will-Schroeder.mp4
wget -c https://archive.org/download/derbycon4/t303-I-Am-The-Cavalry-Year-0-Space-Rogue-and-Beau-Woods.mp4
wget -c https://archive.org/download/derbycon4/t304-University-Education-In-Security-Panel-Bill-Gardner-oncee-Ray-Davidson-Adrian-Crenshaw-Sam-Liles-Rob-Jorgensen.mp4
wget -c https://archive.org/download/derbycon4/t305-What-happened-to-the-A-How-to-leverage-BCPDR-for-your-Info-Sec-Program-Moey.mp4
wget -c https://archive.org/download/derbycon4/t306-Securing-Your-Assets-from-Espionage-Stacey-Banks.mp4
wget -c https://archive.org/download/derbycon4/t307-Hackers-Are-People-Too-Amanda-Berlin-Infosystir.mp4
wget -c https://archive.org/download/derbycon4/t308-Ethical-Control-Ethics-and-Privacy-in-a-Target-Rich-Environment-Kevin-Johnson-and-James-Jardine.mp4
wget -c https://archive.org/download/derbycon4/t309-The-Road-to-Compliancy-Success-Plus-Plus-James-Arlen.mp4
wget -c https://archive.org/download/derbycon4/t310-Are-You-a-Janitor-Or-a-Cleaner-John-Stauffacher-and-Matt-Hoy.mp4
wget -c https://archive.org/download/derbycon4/t311-Practical-PowerShell-Programming-for-Professional-People-Ben-Ten-Ben0xA.mp4
wget -c https://archive.org/download/derbycon4/t312-GROK-atlas.mp4
wget -c https://archive.org/download/derbycon4/t313-How-building-a-better-hacker-accidentally-built-a-better-defender-Casey-Ellis.mp4
wget -c https://archive.org/download/derbycon4/t314-Exploring-Layer-2-Network-Security-in-Virtualized-Environments-Ronny-L-Bull-Dr-Jeanna-N-Matthews.mp4
wget -c https://archive.org/download/derbycon4/t315-Hardware-Tamper-Resistance-Why-and-How-Ryan-Lackey.mp4
wget -c https://archive.org/download/derbycon4/t316-Analyzing-Weak-Areas-of-the-Federal-Cloud-Security-Program-Vinny-Troia.mp4
wget -c https://archive.org/download/derbycon4/t317-Proactive-Application-Security-Karthik-Rangarajan.mp4
wget -c https://archive.org/download/derbycon4/t318-Chicken-of-the-APT-Understanding-Targeted-Attackers-with-Incubation-Kyle-Wilhoit.mp4
wget -c https://archive.org/download/derbycon4/t319-Bending-and-Twisting-Networks-Paul-Coggins.mp4
wget -c https://archive.org/download/derbycon4/t320-Bridging-the-gap-between-red-and-blue-Dave-Kennedy-and-Jamie-Murdock.mp4
wget -c https://archive.org/download/derbycon4/t321-CMS-Hacking-Tricks-Greg-Foss.mp4
wget -c https://archive.org/download/derbycon4/t322-Advanced-Incident-Response-with-Bro-Liam-Randall-hectaman.mp4
wget -c https://archive.org/download/derbycon4/t400-Subverting-ML-Detections-for-Fun-and-Profit-Ram-Shankar-Siva-Kumar-John-Walton.mp4
wget -c https://archive.org/download/derbycon4/t401-Secrets-of-DNS-Ron-Bowes.mp4
wget -c https://archive.org/download/derbycon4/t402-Snort-OpenAppID-How-to-Build-an-Open-Source-Next-Generation-Firewall-Adam-Hogan.mp4
wget -c https://archive.org/download/derbycon4/t403-GET-A-Grip-on-Your-Hustle-Glassdoor-Exfil-Toolkit-Parker-Schmitt-Kyle-Stone-essobi-Chris-Hodges-g11tch.mp4
wget -c https://archive.org/download/derbycon4/t404-DNS-Based-Authentication-of-Named-Entities-DANE-Can-we-fix-our-broken-CA-model-Tony-Cargile.mp4
wget -c https://archive.org/download/derbycon4/t405-Exploiting-Browsers-Like-A-Boss-w-WhiteLightning-Bryce-Kunz.mp4
wget -c https://archive.org/download/derbycon4/t406-Real-World-Intrusion-Response-Lessons-from-the-Trenches-Katherine-Trame-and-David-Sharpe.mp4
wget -c https://archive.org/download/derbycon4/t407-Application-Whitelisting-Be-Careful-Where-The-Silver-Bullet-Is-Aimed-David-McCartney.mp4
wget -c https://archive.org/download/derbycon4/t408-Making-Mongo-Cry-Attacking-NoSQL-for-Pen-Testers-Russell-Butturini.mp4
wget -c https://archive.org/download/derbycon4/t409-Step-On-In-The-Waters-Fine-An-Introduction-To-Security-Testing-Within-A-Virtualized-Environment-Tom-Moore.mp4
wget -c https://archive.org/download/derbycon4/t410-Give-me-your-data-Obtaining-sensitive-data-without-breaking-in-Dave-Chronister.mp4
wget -c https://archive.org/download/derbycon4/t411-Third-Party-Code-FIX-ALL-THE-THINGS-Kymberlee-Price-Jake-Kouns.mp4
wget -c https://archive.org/download/derbycon4/t412-Just-What-The-Doctor-Ordered-Scott-Erven.mp4
wget -c https://archive.org/download/derbycon4/t413-Powershell-Drink-the-Kool-Aid-Wayne-Pruitt-Zack-Wojton.mp4
wget -c https://archive.org/download/derbycon4/t414-powercat-Mick-Douglas.mp4
wget -c https://archive.org/download/derbycon4/t415-Macro-Malware-Lives-Putting-the-sexy-back-into-MS-Office-document-macros-Joff-Thyer.mp4
wget -c https://archive.org/download/derbycon4/t416-Girl-Fault-Interrupted-Maggie-Jauregui.mp4
wget -c https://archive.org/download/derbycon4/t419-Its-Not-Easy-Being-Purple-Bill-Gardner-Valerie-Thomas-Amanda-Berlin-Eric-Milam-Brandon-McCann-Royce-Davis.mp4
wget -c https://archive.org/download/derbycon4/t420-Control-Flow-Graph-Based-Virus-Scanning-Douglas-Goddard.mp4
wget -c https://archive.org/download/derbycon4/t421-Ok-so-youve-been-pwned-now-what-Jim-Wojno.mp4
wget -c https://archive.org/download/derbycon4/t422-Everybody-gets-clickjacked-Hard-knock-lessons-on-bug-bounties-Jonathan-Cran.mp4
wget -c https://archive.org/download/derbycon4/t423-Are-you-a-Beefeater-focused-on-protecting-your-crown-jewels-Jack-Nichelson.mp4
wget -c https://archive.org/download/derbycon4/t500-NeXpose-For-Automated-Compromise-Detection-Luis-connection-Santana.mp4
wget -c https://archive.org/download/derbycon4/t501-A-girl-some-passion-and-some-tech-stuff-Branden-Miller-and-Emily-Miller.mp4
wget -c https://archive.org/download/derbycon4/t502-InfoSec-from-the-mouth-of-babes-or-an-8-year-old-Reuben-A-Paul-RAPstar-and-Mano-Paul.mp4
wget -c https://archive.org/download/derbycon4/t503-Why-Aim-for-the-Ground-Teaching-Our-School-Kids-All-of-the-Right-Computer-Skills-Phillip-Fitzpatrick.mp4
wget -c https://archive.org/download/derbycon4/t504-NoSQL-Injections-Moving-Beyond-or-11-Matt-Bromiley.mp4
wget -c https://archive.org/download/derbycon4/t505-SWF-Seeking-Lazy-Admin-for-Cross-Domain-Action-Seth-Art.mp4
wget -c https://archive.org/download/derbycon4/t506-Planning-for-Failure-Noah-Beddome.mp4
wget -c https://archive.org/download/derbycon4/t507-The-Social-Engineering-Savants-The-Psychopathic-Profile-Kevin-Miller.mp4
wget -c https://archive.org/download/derbycon4/t508-Hiding-the-breadcrumbs-Forensics-and-anti-forensics-on-SAP-systems-Juan-Perez-Etchegoyen.mp4
wget -c https://archive.org/download/derbycon4/t509-Youre-in-the-butter-zone-now-baby-Chris-Scott.mp4
wget -c https://archive.org/download/derbycon4/t510-Making-BadUSB-Work-For-You-Adam-Caudill-Brandon-Wilson.mp4
wget -c https://archive.org/download/derbycon4/t511-PassCrackNet-When-everything-else-fails-just-crack-hashes-Adam-Ringwood.mp4
wget -c https://archive.org/download/derbycon4/t512-Vulnerability-Assessment-20-John-Askew.mp4
wget -c https://archive.org/download/derbycon4/t513-Social-Engineering-your-progeny-to-be-hackers-Sydney-Liles.mp4
wget -c https://archive.org/download/derbycon4/t514-A-Brief-History-of-Exploitation-Devin-Cook.mp4
wget -c https://archive.org/download/derbycon4/t515-Hunting-Malware-on-Linux-Production-Servers-The-Windigo-Backstory-Olivier-Bilodeau.mp4
wget -c https://archive.org/download/derbycon4/t516-Human-Trafficking-in-the-Digital-Age.mp4
wget -c https://archive.org/download/derbycon4/t517-Cat-Herding-in-the-Wild-Wild-West-What-I-Learned-Running-A-Hackercon-CFP-Nathaniel-Husted.mp4
wget -c https://archive.org/download/derbycon4/t518-How-to-Stop-a-Hack-Jason-Samide.mp4
wget -c https://archive.org/download/derbycon4/t519-We-dont-need-no-stinking-Internet-Greg-Simo.mp4
wget -c https://archive.org/download/derbycon4/t520-ZitMo-NoM-David-Schwartzberg.mp4
wget -c https://archive.org/download/derbycon4/t521-Penetrate-your-OWA-Nate-Power.mp4
wget -c https://archive.org/download/derbycon4/t522-RavenHID-Remote-Badge-Gathering-or-Why-we-sit-in-client-bathrooms.mp4
wget -c https://archive.org/download/derbycon4/t523-Interns-Down-for-What-Tony-Turner.mp4
wget -c https://archive.org/download/derbycon4/t524-i-r-web-app-hacking-and-so-can-you-Brandon-Perry.mp4
wget -c https://archive.org/download/derbycon4/t525-Building-a-Modern-Security-Engineering-Organization-Zane-Lackey.mp4
wget -c https://archive.org/download/derbycon4/t526-Information-Security-Team-Management-How-to-keep-your-edge-while-embracing-the-dark-side-Stephen-C-Gay.mp4
wget -c https://archive.org/download/derbycon4/t527-5min-web-audit-Security-in-the-startup-world-Evan-Johnson.mp4
wget -c https://archive.org/download/derbycon4/t528-Project-SCEVRON-SCan-EVrything-with-ruby.mp4
wget -c https://archive.org/download/derbycon4/t530-Gone-in-60-minutes-a-Practical-Approach-to-Hacking-an-Enterprise-with-Yasuo-Saurabh-Harit-and-Stephen-Hall.mp4
wget -c https://archive.org/download/derbycon4/t531-Snarf-Capitalizing-on-Man-in-the-Middle-Victor-Mata-Josh-Stone.mp4
wget -c https://archive.org/download/derbycon4/t532-Electronic-locks-in-firearms-Oh-My-Travis-Hartman.mp4
wget -c https://archive.org/download/derbycon4/t533-Dolla-Dolla-Bump-Key-Chris-Sistrunk.mp4
wget -c https://archive.org/download/derbycon4/t534-What-Dungeons-Dragons-Taught-Me-About-INFOSEC-Joey-Maresca-l0stkn0wledge.mp4
wget -c https://archive.org/download/derbycon4/t535-Gender-Differences-in-Social-Engineering-Does-Sex-Matter-Shannon-Sistrunk.mp4
wget -c https://archive.org/download/derbycon4/t536-Introduction-to-System-Hardening-Eddie-David.mp4
wget -c https://archive.org/download/derbycon4/t537-Hacking-your-way-into-the-APRS-Network-on-the-Cheap-Mark-Lenigan.mp4
wget -c https://archive.org/download/derbycon4/t538-Building-a-Web-Application-Vulnerability-Management-Program-Jason-Pubal.mp4
wget -c https://archive.org/download/derbycon4/t539-Fighting-Back-Against-SSL-Inspection-or-How-SSL-Should-Work-Jacob-Thompson.mp4
wget -c https://archive.org/download/derbycon4/t540-Physical-Security-From-Locks-to-Dox-Jess-Hires.mp4
wget -c https://archive.org/download/derbycon4/t541-Am-I-an-Imposter-Warren-Kopp.mp4
wget -c https://archive.org/download/derbycon4/t542-Call-of-Community-Modern-Warfare-Ben-Ten-and-Matt-Johnson.mp4
wget -c https://archive.org/download/derbycon4/t543-The-Canary-in-the-Cloud-Scot-Bernerv.mp4
